from agents.base_agent import BaseAgent
from typing import Any
import ollama
import os


class ProjectBuilderAgent(BaseAgent):

    def __init__(self):
        super().__init__(name="ProjectBuilderAgent")
        self.model = "qwen2.5-coder:1.5b"

    def get_name(self) -> str:
        return self.name

    def run(self, state: dict[str, Any]) -> dict[str, Any]:
        query = state.get("query", "")
        print(f"  [ProjectBuilder] Building: '{query}'")

        # Step 1: Generate project structure
        structure_prompt = f"""You are an expert software architect.
Create a complete project structure for: {query}

Reply in this EXACT format:
PROJECT_NAME: name_of_project
FILES:
- filename1.py: description
- filename2.py: description
- requirements.txt: dependencies
- README.md: documentation
COMMANDS:
- command1
- command2"""

        structure_response = ollama.chat(
            model=self.model,
            messages=[{"role": "user", "content": structure_prompt}]
        )
        structure = structure_response.message.content

        # Step 2: Generate code for each file
        code_prompt = f"""You are an expert developer.
Generate complete, working code for this project: {query}

Project structure:
{structure}

Generate code for the main file only. Make it complete and runnable.
Include proper error handling."""

        code_response = ollama.chat(
            model=self.model,
            messages=[{"role": "user", "content": code_prompt}]
        )
        code = code_response.message.content

        # Step 3: Create project folder
        project_name = query.lower().replace(" ", "_").replace("build", "").replace("a", "").strip()[:20]
        project_path = f"data/projects/{project_name}"
        os.makedirs(project_path, exist_ok=True)

        # Save main file
        main_file = f"{project_path}/main.py"
        if "```python" in code:
            actual_code = code.split("```python")[1].split("```")[0].strip()
        elif "```" in code:
            actual_code = code.split("```")[1].split("```")[0].strip()
        else:
            actual_code = code

        with open(main_file, "w") as f:
            f.write(actual_code)

        # Save README
        with open(f"{project_path}/README.md", "w") as f:
            f.write(f"# {project_name}\n\n")
            f.write(f"Generated by ACRE AI Assistant\n\n")
            f.write(f"## Project: {query}\n\n")
            f.write(f"## Structure\n{structure}\n\n")
            f.write(f"## How to run\n```\npython main.py\n```\n")

        answer = f"""✅ Project Created: {project_name}
        
📁 Location: {project_path}

📋 Structure:
{structure}

🚀 Main file created: main.py

To run your project:
1. cd {project_path}
2. pip install -r requirements.txt (if exists)
3. python main.py"""

        print(f"  [ProjectBuilder] Project created at {project_path}")

        return {
            **state,
            "code_result": {
                "code": actual_code,
                "stdout": answer,
                "stderr": "",
                "error": False,
                "confidence": 0.9,
            }
        }